const usersData = [
  {
    id: 1,
    name: "Hand-Langosh",
    address: "9 Delaware Terrace",
    open_time: "1:44 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account1",
    password: "1",
  },
  {
    id: 2,
    name: "Friesen LLC",
    address: "74561 Little Fleur Road",
    open_time: "12:53 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account2",
    password: "1",
  },
  {
    id: 3,
    name: "Williamson, Kohler and Kilback",
    address: "792 Truax Way",
    open_time: "6:04 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account3",
    password: "1",
  },
  {
    id: 4,
    name: "Goldner, Legros and Rowe",
    address: "9 Goodland Pass",
    open_time: "2:42 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account4",
    password: "1",
  },
  {
    id: 5,
    name: "Hessel Inc",
    address: "323 Springs Road",
    open_time: "7:49 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account5",
    password: "1",
  },
  {
    id: 6,
    name: "Lockman Group",
    address: "32 Del Mar Road",
    open_time: "10:17 AM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account6",
    password: "1",
  },
  {
    id: 7,
    name: "Schaefer LLC",
    address: "8798 Del Sol Junction",
    open_time: "4:06 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account7",
    password: "1",
  },
  {
    id: 8,
    name: "Bergstrom Group",
    address: "9 Mifflin Circle",
    open_time: "8:42 AM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account8",
    password: "1",
  },
  {
    id: 9,
    name: "Monahan-Hansen",
    address: "720 Mandrake Point",
    open_time: "6:56 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account9",
    password: "1",
  },
  {
    id: 10,
    name: "Beer, Connelly and Barrows",
    address: "864 Washington Parkway",
    open_time: "8:28 AM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account10",
    password: "1",
  },
  {
    id: 11,
    name: "Ziemann, Tillman and Leuschke",
    address: "648 6th Hill",
    open_time: "3:28 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account11",
    password: "1",
  },
  {
    id: 12,
    name: "Raynor, Wolf and Simonis",
    address: "6 Miller Circle",
    open_time: "11:08 AM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account12",
    password: "1",
  },
  {
    id: 13,
    name: "Koepp, Bogisich and Pacocha",
    address: "1259 Lake View Way",
    open_time: "12:26 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account13",
    password: "1",
  },
  {
    id: 14,
    name: "Goyette, Feil and Donnelly",
    address: "577 Autumn Leaf Way",
    open_time: "12:55 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account14",
    password: "1",
  },
  {
    id: 15,
    name: "Towne Group",
    address: "74659 Ludington Road",
    open_time: "1:38 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account15",
    password: "1",
  },
  {
    id: 16,
    name: "Luettgen and Sons",
    address: "4821 Rowland Street",
    open_time: "5:50 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account16",
    password: "1",
  },
  {
    id: 17,
    name: "Kshlerin, Murazik and Yundt",
    address: "534 Old Gate Place",
    open_time: "7:36 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account17",
    password: "1",
  },
  {
    id: 18,
    name: "Daniel LLC",
    address: "3906 Upham Street",
    open_time: "7:41 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account18",
    password: "1",
  },
  {
    id: 19,
    name: "Frami-Simonis",
    address: "949 Maple Circle",
    open_time: "11:57 AM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account19",
    password: "1",
  },
  {
    id: 20,
    name: "Koch-Johnson",
    address: "627 Texas Pass",
    open_time: "12:46 PM",
    store_type: "Hair Salon",
    phone_number: "0987654321",
    username: "account20",
    password: "1",
  },
];

export default usersData;
